// next-app/src/components/ui/Slider.tsx
"use client";

import React, { useEffect, useState } from "react";
import Link from "next/link";

export default function Slider() {
    const [isAuthenticated, setIsAuthenticated] = useState(false);

    useEffect(() => {
        setIsAuthenticated(!!sessionStorage.getItem("authToken") || !!sessionStorage.getItem("user"));
    }, []);

    const slide = {
        title: "Empowering Growth Through Skill-Based Talent Strategies",
        description: "A transformative approach to talent management for the Supply Chain, Logistics, and Cargo industries.",
        image: "https://tirwin-media-storage.s3.us-east-1.amazonaws.com/static-images/banner-image-slider.png",
    };

    return (
        <div className="banner d-flex flex-column flex-md-row align-items-center">
            <div className="banner-content text-md-left">
                <h1 className="animate-title">{slide.title}</h1>
                <p className="animate-description" dangerouslySetInnerHTML={{ __html: slide.description }}></p>

                <div className="button-group">
                    {!isAuthenticated ? (
                        <Link href="/auth/register" className="btn btn-primary">
                            Start your Journey with us
                        </Link>
                    ) : (
                        <>
                            <Link href="/webinar/masterclass" className="btn btn-primary">
                                Master Classes
                            </Link>
                            <Link href="/webinar/events" className="btn btn-primary ms-2">
                                Events
                            </Link>
                            <Link href="/webinar/training" className="btn btn-primary ms-2">
                                Training
                            </Link>
                        </>
                    )}
                </div>
            </div>

            <div className="banner-image">
                <img src={slide.image} alt="Banner Image" className="img-fluid" />
            </div>
        </div>
    );
}

// src/app/components/slider/slider.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: "app-slider",
  templateUrl: "./slider.component.html",
  styleUrls: ["./slider.component.css"],
})
export class SliderComponent implements OnInit {
  isAuthenticated: boolean = false;

  //Tirwin Talent™: Empowering Growth Through Skill-Based Talent Strategies

  slide = {
    title:
      "Empowering Growth Through Skill-Based Talent Strategies",
    description:
      "A transformative approach to talent management for the Supply Chain, Logistics, and Cargo industries.",
    buttonText: "Try Now →",
    buttonLink: "#",
    image:
      "https://tirwin-media-storage.s3.us-east-1.amazonaws.com/static-images/banner-image-slider.png",
  };

  ngOnInit() {
    this.checkAuthentication();
  }

  checkAuthentication() {
    this.isAuthenticated = !!sessionStorage.getItem("authToken"); // Check if user is logged in
  }
}
<div class="banner d-flex flex-column flex-md-row align-items-center">
  
  <!-- Left: Banner Content -->
  <div class="banner-content text-md-left">
    <h1 class="animate-title">{{ slide.title }}</h1>
    <p class="animate-description" [innerHTML]="slide.description"></p>

    <!-- Show Different Content Based on Login Status -->
    <div class="button-group">
      <ng-container *ngIf="!isAuthenticated">
        <a href="/auth/register" class="btn btn-primary">Start your Journey with us</a>
      </ng-container>

      <ng-container *ngIf="isAuthenticated">
        <a href="/webinar/masterclass" class="btn btn-primary">Master Classes</a>
      </ng-container>
      <ng-container *ngIf="isAuthenticated">
        <a href="/webinar/events" class="btn btn-primary">Events</a>
      </ng-container>
      <ng-container *ngIf="isAuthenticated">
        <a href="/webinar/training" class="btn btn-primary">Training</a>
      </ng-container>
    </div>
  </div>

  <!-- Right: Banner Image -->
  <div class="banner-image">
    <img [src]="slide.image" alt="Banner Image" class="img-fluid">
  </div>

</div>
