// src/app/pages/terms-conditions/terms-conditions.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-terms-conditions',
  templateUrl: './terms-conditions.component.html',
  styleUrl: './terms-conditions.component.css'
})
export class TermsConditionsComponent implements OnInit {
  
  ngOnInit() {
    console.log('TermsConditionsComponent loaded successfully!');
    // Scroll to top when component loads
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
}

<!-- Terms and Conditions Page -->
<div class="terms-conditions-page">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="page-header">
                    <h1>Terms and Conditions</h1>
                    <p class="last-updated">
                        <strong>Effective Date:</strong> July 23, 2025<br>
                        <strong>Last Updated:</strong> July 23, 2025
                    </p>
                </div>
                <div class="terms-content">
                    <section class="terms-section">
                        <p>Welcome to <strong>tirwintalent.com</strong>. These Terms and Conditions ("Terms") govern your use of our platform ("Site") and participation in masterclasses, events, and training sessions ("Webinars"), both free and paid. By using the Site, you agree to comply with these Terms.</p>
                    </section>
                    <section class="terms-section">
                        <h2>1. Definitions</h2>
                        <ul>
                            <li><strong>User:</strong> Anyone who registers for or attends a webinar.</li>
                            <li><strong>Host:</strong> Individual or organization conducting a webinar.</li>
                            <li><strong>Paid Webinar:</strong> Any session or training requiring payment.</li>
                            <li><strong>Free Webinar:</strong> Webinars with no associated cost.</li>
                        </ul>
                    </section>
                    <section class="terms-section">
                        <h2>2. Eligibility</h2>
                        <p>You must be at least 18 years old to use this Site or have parental/guardian consent. By registering, you confirm the information provided is accurate and complete.</p>
                    </section>
                    <section class="terms-section">
                        <h2>3. Account Registration</h2>
                        <ul>
                            <li>You agree to maintain the confidentiality of your account.</li>
                            <li>You are responsible for all activities under your account.</li>
                        </ul>
                    </section>
                    <section class="terms-section">
                        <h2>4. Use of Platform</h2>
                        <ul>
                            <li>You may not use the Site for any illegal or unauthorized purpose.</li>
                            <li>Misuse of content, platform infrastructure, or disruption of service is strictly prohibited.</li>
                        </ul>
                    </section>
                    <section class="terms-section">
                        <h2>5. Booking & Payments</h2>
                        <ul>
                            <li>Free webinars are accessible upon registration.</li>
                            <li>Paid webinars require advance payment through our designated payment gateway.</li>
                            <li>Prices are subject to change without prior notice.</li>
                        </ul>
                    </section>
                    <section class="terms-section">
                        <h2>6. Refund Policy</h2>
                        <h3>6.1. User-Initiated Refunds</h3>
                        <ul>
                            <li><strong>Paid Webinars:</strong></li>
                            <ul>
                                <li>Kindly contact us at <a href="mailto:tirwin.communications&#64;tirwin.in">tirwin.communications&#64;tirwin.in</a> for assistance.We will process your refund within 7-10 working days.</li>
                            </ul>
                            <li>No refund for free webinars unless technical issues prevent access (to be verified).</li>
                        </ul>
                        <h3>6.2. Host/Platform-Initiated Refunds</h3>
                        <ul>
                            <li>If a webinar is cancelled or rescheduled by the host or the platform, users may opt for:</li>
                            <ul>
                                <li>A full refund</li>
                                <li>A credit for future webinars</li>
                                <li>Rescheduled participation at no additional cost</li>
                            </ul>
                            <li>Refunds will be processed within <strong>7–10 business days</strong>.</li>
                        </ul>
                    </section>
                    <section class="terms-section">
                        <h2>7. Rescheduling Policy</h2>
                        <h3>7.1. User Requests</h3>
                        <ul>
                            <li>Rescheduling requests must be made at least <strong>48 hours in advance</strong>.</li>
                            <li>Approval is subject to host availability and at the sole discretion of the platform.</li>
                        </ul>
                        <h3>7.2. Host Rescheduling</h3>
                        <ul>
                            <li>Hosts may reschedule due to unforeseen circumstances.</li>
                            <li>Users will be notified at least <strong>24 hours in advance</strong>, with options to accept the new time, opt for another session, or request a refund.</li>
                        </ul>
                    </section>
                    <section class="terms-section">
                        <h2>8. Cancellations</h2>
                        <h3>8.1. User Cancellations</h3>
                        <ul>
                            <li>Users can cancel from their dashboard or by contacting support.</li>
                            <li>Refund policies as per Section 6 apply.</li>
                        </ul>
                        <h3>8.2. Host/Platform Cancellations</h3>
                        <ul>
                            <li>We reserve the right to cancel or postpone any webinar.</li>
                            <li>Affected users will be offered alternatives or full refunds.</li>
                        </ul>
                    </section>
                    <section class="terms-section">
                        <h2>9. Webinar Access and Conduct</h2>
                        <ul>
                            <li>Access links will be provided 12–24 hours before the event.</li>
                            <li>Users must not share or distribute webinar access credentials.</li>
                            <li>Recording or redistributing content without permission is prohibited.</li>
                            <li>Disruptive or abusive behavior will result in removal and a permanent ban.</li>
                        </ul>
                    </section>
                    <section class="terms-section">
                        <h2>10. Intellectual Property</h2>
                        <p>All webinar content, materials, and recordings are the intellectual property of the host or the platform. You may not reproduce, republish, or distribute any materials without written consent.</p>
                    </section>
                    <section class="terms-section">
                        <h2>11. Limitation of Liability</h2>
                        <p>The platform is not responsible for any direct, indirect, incidental, or consequential damages arising from the use or inability to access a webinar. We are not liable for host behavior, quality of content, or technical interruptions outside our control.</p>
                    </section>
                    <section class="terms-section">
                        <h2>12. Termination</h2>
                        <p>We reserve the right to suspend or terminate any account found in violation of these Terms, with or without notice.</p>
                    </section>
                    <section class="terms-section">
                        <h2>13. Modifications to Terms</h2>
                        <p>We may update these Terms periodically. Continued use of the platform constitutes acceptance of the revised Terms.</p>
                    </section>
                    <section class="terms-section">
                        <h2>14. Contact Information</h2>
                        <div class="contact-info">
                            <p>For any queries, cancellations, or support:</p>
                            <p>📧 Email: <a href="mailto:tirwin.communications&#64;tirwin.in">tirwin.communications&#64;tirwin.in</a></p>
                            <p>📞 Phone: +91-9841970466</p>
                        </div>
                    </section>
                    <section class="terms-section">
                        <h2>15. Governing Law</h2>
                        <p>These Terms are governed by the laws of India, without regard to conflict of law principles.</p>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>

// next-app/src/app/(main)/terms-conditions/page.tsx
import React from "react";
import "./terms.css";

export const metadata = {
    title: "Terms and Conditions | Tirwin Talent",
};

export default function TermsConditionsPage() {
    return (
        <div className="terms-conditions-page">
            <div className="container">
                <div className="row">
                    <div className="col-12">
                        <div className="page-header">
                            <h1>Terms and Conditions</h1>
                            <p className="last-updated">
                                <strong>Effective Date:</strong> July 23, 2025<br />
                                <strong>Last Updated:</strong> July 23, 2025
                            </p>
                        </div>
                        <div className="terms-content">
                            <section className="terms-section">
                                <p>
                                    Welcome to <strong>tirwintalent.com</strong>. These Terms and
                                    Conditions (&quot;Terms&quot;) govern your use of our platform (&quot;Site&quot;)
                                    and participation in masterclasses, events, and training
                                    sessions (&quot;Webinars&quot;), both free and paid. By using the Site,
                                    you agree to comply with these Terms.
                                </p>
                            </section>
                            <section className="terms-section">
                                <h2>1. Definitions</h2>
                                <ul>
                                    <li><strong>User:</strong> Anyone who registers for or attends a webinar.</li>
                                    <li><strong>Host:</strong> Individual or organization conducting a webinar.</li>
                                    <li><strong>Paid Webinar:</strong> Any session or training requiring payment.</li>
                                    <li><strong>Free Webinar:</strong> Webinars with no associated cost.</li>
                                </ul>
                            </section>
                            <section className="terms-section">
                                <h2>2. Eligibility</h2>
                                <p>
                                    You must be at least 18 years old to use this Site or have
                                    parental/guardian consent. By registering, you confirm the
                                    information provided is accurate and complete.
                                </p>
                            </section>
                            <section className="terms-section">
                                <h2>3. Account Registration</h2>
                                <ul>
                                    <li>You agree to maintain the confidentiality of your account.</li>
                                    <li>You are responsible for all activities under your account.</li>
                                </ul>
                            </section>
                            <section className="terms-section">
                                <h2>4. Use of Platform</h2>
                                <ul>
                                    <li>You may not use the Site for any illegal or unauthorized purpose.</li>
                                    <li>
                                        Misuse of content, platform infrastructure, or disruption of
                                        service is strictly prohibited.
                                    </li>
                                </ul>
                            </section>
                            <section className="terms-section">
                                <h2>5. Booking & Payments</h2>
                                <ul>
                                    <li>Free webinars are accessible upon registration.</li>
                                    <li>
                                        Paid webinars require advance payment through our designated
                                        payment gateway.
                                    </li>
                                    <li>Prices are subject to change without prior notice.</li>
                                </ul>
                            </section>
                            <section className="terms-section">
                                <h2>6. Refund Policy</h2>
                                <h3>6.1. User-Initiated Refunds</h3>
                                <ul>
                                    <li><strong>Paid Webinars:</strong></li>
                                    <ul>
                                        <li>
                                            Kindly contact us at{" "}
                                            <a href="mailto:tirwin.communications@tirwin.in">
                                                tirwin.communications@tirwin.in
                                            </a>{" "}
                                            for assistance.We will process your refund within 7-10
                                            working days.
                                        </li>
                                    </ul>
                                    <li>
                                        No refund for free webinars unless technical issues prevent
                                        access (to be verified).
                                    </li>
                                </ul>
                                <h3>6.2. Host/Platform-Initiated Refunds</h3>
                                <ul>
                                    <li>
                                        If a webinar is cancelled or rescheduled by the host or the
                                        platform, users may opt for:
                                    </li>
                                    <ul>
                                        <li>A full refund</li>
                                        <li>A credit for future webinars</li>
                                        <li>Rescheduled participation at no additional cost</li>
                                    </ul>
                                    <li>
                                        Refunds will be processed within <strong>7–10 business days</strong>.
                                    </li>
                                </ul>
                            </section>
                            <section className="terms-section">
                                <h2>7. Rescheduling Policy</h2>
                                <h3>7.1. User Requests</h3>
                                <ul>
                                    <li>
                                        Rescheduling requests must be made at least{" "}
                                        <strong>48 hours in advance</strong>.
                                    </li>
                                    <li>
                                        Approval is subject to host availability and at the sole
                                        discretion of the platform.
                                    </li>
                                </ul>
                                <h3>7.2. Host Rescheduling</h3>
                                <ul>
                                    <li>Hosts may reschedule due to unforeseen circumstances.</li>
                                    <li>
                                        Users will be notified at least <strong>24 hours in advance</strong>,
                                        with options to accept the new time, opt for another session,
                                        or request a refund.
                                    </li>
                                </ul>
                            </section>
                            <section className="terms-section">
                                <h2>8. Cancellations</h2>
                                <h3>8.1. User Cancellations</h3>
                                <ul>
                                    <li>
                                        Users can cancel from their dashboard or by contacting
                                        support.
                                    </li>
                                    <li>Refund policies as per Section 6 apply.</li>
                                </ul>
                                <h3>8.2. Host/Platform Cancellations</h3>
                                <ul>
                                    <li>We reserve the right to cancel or postpone any webinar.</li>
                                    <li>
                                        Affected users will be offered alternatives or full refunds.
                                    </li>
                                </ul>
                            </section>
                            <section className="terms-section">
                                <h2>9. Webinar Access and Conduct</h2>
                                <ul>
                                    <li>
                                        Access links will be provided 12–24 hours before the event.
                                    </li>
                                    <li>
                                        Users must not share or distribute webinar access credentials.
                                    </li>
                                    <li>
                                        Recording or redistributing content without permission is
                                        prohibited.
                                    </li>
                                    <li>
                                        Disruptive or abusive behavior will result in removal and a
                                        permanent ban.
                                    </li>
                                </ul>
                            </section>
                            <section className="terms-section">
                                <h2>10. Intellectual Property</h2>
                                <p>
                                    All webinar content, materials, and recordings are the
                                    intellectual property of the host or the platform. You may not
                                    reproduce, republish, or distribute any materials without
                                    written consent.
                                </p>
                            </section>
                            <section className="terms-section">
                                <h2>11. Limitation of Liability</h2>
                                <p>
                                    The platform is not responsible for any direct, indirect,
                                    incidental, or consequential damages arising from the use or
                                    inability to access a webinar. We are not liable for host
                                    behavior, quality of content, or technical interruptions
                                    outside our control.
                                </p>
                            </section>
                            <section className="terms-section">
                                <h2>12. Termination</h2>
                                <p>
                                    We reserve the right to suspend or terminate any account found
                                    in violation of these Terms, with or without notice.
                                </p>
                            </section>
                            <section className="terms-section">
                                <h2>13. Modifications to Terms</h2>
                                <p>
                                    We may update these Terms periodically. Continued use of the
                                    platform constitutes acceptance of the revised Terms.
                                </p>
                            </section>
                            <section className="terms-section">
                                <h2>14. Contact Information</h2>
                                <div className="contact-info">
                                    <p>For any queries, cancellations, or support:</p>
                                    <p>
                                        📧 Email:{" "}
                                        <a href="mailto:tirwin.communications@tirwin.in">
                                            tirwin.communications@tirwin.in
                                        </a>
                                    </p>
                                    <p>📞 Phone: +91-9841970466</p>
                                </div>
                            </section>
                            <section className="terms-section">
                                <h2>15. Governing Law</h2>
                                <p>
                                    These Terms are governed by the laws of India, without regard
                                    to conflict of law principles.
                                </p>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
