// src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-footer',
  templateUrl: './footer.component.html',
  styleUrl: './footer.component.css'
})
export class FooterComponent {

  constructor(private router: Router) {}

  scrollToTop() {
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }

  navigateToTermsAndConditions() {
    this.router.navigate(['/terms-conditions']);
    this.scrollToTop();
  }

  navigateToPrivacyPolicy() {
    this.router.navigate(['/privacy-policy']);
    this.scrollToTop();
  }

  navigateToPricingPolicy() {
    this.router.navigate(['/pricing-policy']);
    this.scrollToTop();
  }
}

<!-- Footer -->
<footer id="footer">
    <div class="footer-content">
        <div class="container">
            <div class="row gap-y">
                <div class="col-md-6 col-xl-4">
                    <p>
                        <a href="https://tirwin.in" target="_blank"><img class="footer-logo" src="https://www.tirwin.in/images/tirwin-logo.png" alt="logo"></a>
                    </p>
                    <p><b>Tirwin Talent</b> – A specialized webinar platform by <a href="https://www.tirwin.in/" target="_blank" rel="noopener"><b>TIRWIN Management PVT. LTD</b></a>, designed to empower logistics professionals.</p>
                    
                </div>
                <div class="col-md-6 col-xl-4">
                <p>
                    <a href="https://neolumina.in" target="_blank"><img class="footer-logo" src="assets/images/nts-logo.png"
                            alt="logo"></a>
                            
                </p>
                <p>In collaboration with <a href="https://neolumina.in" target="_blank"><b>Neolumina Technology Solutions</b></a> –
                    Illuminating the Future.</p>
                </div>
                
                <div class="col-6 col-md-3 col-xl-2">
                    <!-- Footer widget area 1 -->
                    <div class="widget">
                        <h4>TIRWIN</h4>
                        <ul class="list">
                            <li><a href="https://tirwin.in/about/">About Us</a></li>
                            <li><a href="#">What we Offer</a></li>
                            <li><a href="https://tirwin.in/about/our-team.php">Leadership</a></li>
                            <li><a href="#">Careers</a></li>
                            <li><a href="https://tirwin.in/contact.php" target="_blank">Contact Us</a></li>
                            <li><a href="javascript:void(0)" (click)="navigateToTermsAndConditions()">Terms & Conditions</a></li>
                            <li><a href="javascript:void(0)" (click)="navigateToPrivacyPolicy()">Privacy Policy</a></li>
                            <li><a href="javascript:void(0)" (click)="navigateToPricingPolicy()">Pricing Policy</a></li>
                        </ul>
                    </div>
                    <!-- end: Footer widget area 1 -->
                </div>
                <div class="col-6 col-md-6 col-xl-2">
                    <!-- Social icons -->
                    <h5>FOLLOW US</h5>
                    <div class="social-icons social-icons-colored social-icons-rounded float-left">
                        <ul>
                            <li class="social-rss"><a href="#"><i class="fa fa-rss"></i></a></li>
                            <li class="social-facebook"><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                            <li class="social-twitter"><a href="#"><i class="fab fa-twitter"></i></a></li>
                            <li class="social-youtube"><a href="#"><i class="fab fa-youtube"></i></a></li>
                        </ul>
                    </div>
                    <!-- end: Social icons -->
                </div>
            </div>
        </div>
    </div>
    <div class="copyright-content">
        <div class="container">
            <div class="copyright-text text-center">&copy; 2025 TIRWIN Management PVT. LTD All
                Rights Reserved.<a href="https://www.tirwin.in/" target="_blank" rel="noopener">TIRWIN</a>
            </div>
        </div>
    </div>
</footer>
<!-- end: Footer -->

// next-app/src/components/layout/Footer.tsx
"use client";

import React from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";

export default function Footer() {
    const router = useRouter();

    const scrollToTop = () => {
        window.scrollTo({ top: 0, behavior: "smooth" });
    };

    const navigateToTermsAndConditions = (e: React.MouseEvent) => {
        e.preventDefault();
        router.push("/terms-conditions");
        scrollToTop();
    };

    const navigateToPrivacyPolicy = (e: React.MouseEvent) => {
        e.preventDefault();
        router.push("/privacy-policy");
        scrollToTop();
    };

    const navigateToPricingPolicy = (e: React.MouseEvent) => {
        e.preventDefault();
        router.push("/pricing-policy");
        scrollToTop();
    };

    return (
        <footer id="footer">
            <div className="footer-content">
                <div className="container">
                    <div className="row gap-y">
                        <div className="col-md-6 col-xl-4">
                            <p>
                                <a href="https://tirwin.in" target="_blank" rel="noopener noreferrer">
                                    <img
                                        className="footer-logo"
                                        src="https://www.tirwin.in/images/tirwin-logo.png"
                                        alt="logo"
                                    />
                                </a>
                            </p>
                            <p>
                                <b>Tirwin Talent</b> – A specialized webinar platform by{" "}
                                <a href="https://www.tirwin.in/" target="_blank" rel="noopener noreferrer">
                                    <b>TIRWIN Management PVT. LTD</b>
                                </a>
                                , designed to empower logistics professionals.
                            </p>
                        </div>
                        <div className="col-md-6 col-xl-4">
                            <p>
                                <a href="https://neolumina.in" target="_blank" rel="noopener noreferrer">
                                    <img
                                        className="footer-logo"
                                        src="/assets/images/nts-logo.png"
                                        alt="logo"
                                    />
                                </a>
                            </p>
                            <p>
                                In collaboration with{" "}
                                <a href="https://neolumina.in" target="_blank" rel="noopener noreferrer">
                                    <b>Neolumina Technology Solutions</b>
                                </a>{" "}
                                – Illuminating the Future.
                            </p>
                        </div>

                        <div className="col-6 col-md-3 col-xl-2">
                            <div className="widget">
                                <h4>TIRWIN</h4>
                                <ul className="list">
                                    <li>
                                        <Link href="/about-us">About Us</Link>
                                    </li>
                                    <li>
                                        <Link href="/brand-awareness">Branding</Link>
                                    </li>
                                    <li>
                                        <a href="#">What we Offer</a>
                                    </li>
                                    <li>
                                        <Link href="/leadership">Leadership</Link>
                                    </li>
                                    <li>
                                        <a href="#">Careers</a>
                                    </li>
                                    <li>
                                        <Link href="/contact-us">Contact Us</Link>
                                    </li>
                                    <li>
                                        <a href="#" onClick={navigateToTermsAndConditions}>
                                            Terms & Conditions
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" onClick={navigateToPrivacyPolicy}>
                                            Privacy Policy
                                        </a>
                                    </li>
                                    <li>
                                        <a href="#" onClick={navigateToPricingPolicy}>
                                            Pricing Policy
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>

                        <div className="col-6 col-md-6 col-xl-2">
                            <h5>FOLLOW US</h5>
                            <div className="social-icons social-icons-colored social-icons-rounded float-left">
                                <ul>
                                    <li className="social-facebook">
                                        <a href="#" target="_blank" rel="noopener noreferrer" aria-label="Facebook">
                                            <i className="fab fa-facebook-f"></i>
                                        </a>
                                    </li>
                                    <li className="social-linkedin">
                                        <a href="https://www.linkedin.com/in/tirwin-talent-0a90aa31a/" target="_blank" rel="noopener noreferrer" aria-label="LinkedIn">
                                            <i className="fab fa-linkedin-in"></i>
                                        </a>
                                    </li>
                                    <li className="social-instagram">
                                        <a href="https://www.instagram.com/tirwin.management/" target="_blank" rel="noopener noreferrer" aria-label="Instagram">
                                            <i className="fab fa-instagram"></i>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div className="copyright-content">
                <div className="container">
                    <div className="copyright-text text-center">
                        &copy; 2025 TIRWIN Management PVT. LTD All Rights Reserved.{" "}
                        <a href="https://www.tirwin.in/" target="_blank" rel="noopener noreferrer">
                            TIRWIN
                        </a>
                    </div>
                </div>
            </div>
        </footer>
    );
}
