// src/app/pages/privacy-policy/privacy-policy.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-privacy-policy',
  templateUrl: './privacy-policy.component.html',
  styleUrl: './privacy-policy.component.css'
})
export class PrivacyPolicyComponent implements OnInit {
  
  ngOnInit() {
    console.log('PrivacyPolicyComponent loaded successfully!');
    // Scroll to top when component loads
    window.scrollTo({ top: 0, behavior: 'smooth' });
  }
} 
<!-- Privacy Policy Page -->
<div class="privacy-policy-page">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="page-header">
                    <h1>Privacy Policy</h1>
                    <p class="last-updated">
                        <strong>Effective Date:</strong> August 4, 2025<br>
                        <strong>Last Updated:</strong> August 4, 2025
                    </p>
                </div>
                <div class="privacy-content">
                    <section class="privacy-section">
                        <p>At <strong>Tirwin Talent</strong> (https://tirwintalent.com), we value your privacy and are committed to protecting your personal information. This Privacy Policy explains how we collect, use, disclose, and safeguard your data when you visit our website or use our services.</p>
                    </section>
                    <section class="privacy-section">
                        <h2>1. Information We Collect</h2>
                        <ul>
                            <li><strong>Personal Information:</strong> Name, email address, phone number, billing address, etc.</li>
                            <li><strong>Account Information:</strong> Username, passwords, user preferences.</li>
                            <li><strong>Payment Information:</strong> Credit/debit card details (processed securely via third-party payment gateway).</li>
                            <li><strong>Usage Data:</strong> IP address, browser type, operating system, device type, access times, and pages viewed.</li>
                        </ul>
                    </section>
                    <section class="privacy-section">
                        <h2>2. How We Use Your Information</h2>
                        <ul>
                            <li>To create and manage your account</li>
                            <li>To provide webinar services and customer support</li>
                            <li>To process transactions and send confirmations</li>
                            <li>To communicate with you about promotions, updates, or policy changes</li>
                            <li>To improve user experience and service delivery</li>
                        </ul>
                    </section>
                    <section class="privacy-section">
                        <h2>3. Data Sharing and Disclosure</h2>
                        <p>We do not sell your data. We may share information with:</p>
                        <ul>
                            <li>Trusted third-party service providers (payment gateways, email marketing platforms)</li>
                            <li>Legal authorities, when required by law or legal process</li>
                            <li>Webinar hosts, in case of event registrations and attendance tracking</li>
                        </ul>
                    </section>
                    <section class="privacy-section">
                        <h2>4. Data Retention</h2>
                        <p>We retain your data only for as long as necessary to provide our services and comply with legal obligations.</p>
                    </section>
                    <section class="privacy-section">
                        <h2>5. Cookies and Tracking</h2>
                        <p>We use cookies and similar technologies to improve functionality and analyze usage. You can modify your browser settings to disable cookies.</p>
                    </section>
                    <section class="privacy-section">
                        <h2>6. Security</h2>
                        <p>We implement industry-standard security measures to protect your data. However, no method is 100% secure.</p>
                    </section>
                    <section class="privacy-section">
                        <h2>7. Your Rights</h2>
                        <ul>
                            <li>Access, correct, or delete your personal data</li>
                            <li>Opt-out of marketing communications</li>
                            <li>Withdraw consent where applicable</li>
                        </ul>
                    </section>
                    <section class="privacy-section">
                        <h2>8. Children's Privacy</h2>
                        <p>Our services are not intended for children under 13. We do not knowingly collect data from minors.</p>
                    </section>
                    <section class="privacy-section">
                        <h2>9. Updates to this Policy</h2>
                        <p>We may update this Privacy Policy. Changes will be posted on this page with updated effective dates.</p>
                    </section>
                    <section class="privacy-section">
                        <h2>10. Contact Information</h2>
                        <div class="contact-info">
                            <p>For any questions or concerns about this Privacy Policy:</p>
                            <p>📧 Email: <a href="mailto:tirwin.communications&#64;tirwin.in">tirwin.communications&#64;tirwin.in</a></p>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </div>
</div>

// next-app/src/app/(main)/privacy-policy/page.tsx
import React from "react";
import "./privacy.css";

export const metadata = {
    title: "Privacy Policy | Tirwin Talent",
};

export default function PrivacyPolicyPage() {
    return (
        <div className="privacy-policy-page">
            <div className="container">
                <div className="row">
                    <div className="col-12">
                        <div className="page-header">
                            <h1>Privacy Policy</h1>
                            <p className="last-updated">
                                <strong>Effective Date:</strong> August 4, 2025<br />
                                <strong>Last Updated:</strong> August 4, 2025
                            </p>
                        </div>
                        <div className="privacy-content">
                            <section className="privacy-section">
                                <p>
                                    At <strong>Tirwin Talent</strong> (https://tirwintalent.com), we
                                    value your privacy and are committed to protecting your personal
                                    information. This Privacy Policy explains how we collect, use,
                                    disclose, and safeguard your data when you visit our website or
                                    use our services.
                                </p>
                            </section>
                            <section className="privacy-section">
                                <h2>1. Information We Collect</h2>
                                <ul>
                                    <li>
                                        <strong>Personal Information:</strong> Name, email address,
                                        phone number, billing address, etc.
                                    </li>
                                    <li>
                                        <strong>Account Information:</strong> Username, passwords,
                                        user preferences.
                                    </li>
                                    <li>
                                        <strong>Payment Information:</strong> Credit/debit card
                                        details (processed securely via third-party payment gateway).
                                    </li>
                                    <li>
                                        <strong>Usage Data:</strong> IP address, browser type,
                                        operating system, device type, access times, and pages viewed.
                                    </li>
                                </ul>
                            </section>
                            <section className="privacy-section">
                                <h2>2. How We Use Your Information</h2>
                                <ul>
                                    <li>To create and manage your account</li>
                                    <li>To provide webinar services and customer support</li>
                                    <li>To process transactions and send confirmations</li>
                                    <li>
                                        To communicate with you about promotions, updates, or policy
                                        changes
                                    </li>
                                    <li>To improve user experience and service delivery</li>
                                </ul>
                            </section>
                            <section className="privacy-section">
                                <h2>3. Data Sharing and Disclosure</h2>
                                <p>We do not sell your data. We may share information with:</p>
                                <ul>
                                    <li>
                                        Trusted third-party service providers (payment gateways, email
                                        marketing platforms)
                                    </li>
                                    <li>
                                        Legal authorities, when required by law or legal process
                                    </li>
                                    <li>
                                        Webinar hosts, in case of event registrations and attendance
                                        tracking
                                    </li>
                                </ul>
                            </section>
                            <section className="privacy-section">
                                <h2>4. Data Retention</h2>
                                <p>
                                    We retain your data only for as long as necessary to provide our
                                    services and comply with legal obligations.
                                </p>
                            </section>
                            <section className="privacy-section">
                                <h2>5. Cookies and Tracking</h2>
                                <p>
                                    We use cookies and similar technologies to improve functionality
                                    and analyze usage. You can modify your browser settings to
                                    disable cookies.
                                </p>
                            </section>
                            <section className="privacy-section">
                                <h2>6. Security</h2>
                                <p>
                                    We implement industry-standard security measures to protect your
                                    data. However, no method is 100% secure.
                                </p>
                            </section>
                            <section className="privacy-section">
                                <h2>7. Your Rights</h2>
                                <ul>
                                    <li>Access, correct, or delete your personal data</li>
                                    <li>Opt-out of marketing communications</li>
                                    <li>Withdraw consent where applicable</li>
                                </ul>
                            </section>
                            <section className="privacy-section">
                                <h2>8. Children&apos;s Privacy</h2>
                                <p>
                                    Our services are not intended for children under 13. We do not
                                    knowingly collect data from minors.
                                </p>
                            </section>
                            <section className="privacy-section">
                                <h2>9. Updates to this Policy</h2>
                                <p>
                                    We may update this Privacy Policy. Changes will be posted on this
                                    page with updated effective dates.
                                </p>
                            </section>
                            <section className="privacy-section">
                                <h2>10. Contact Information</h2>
                                <div className="contact-info">
                                    <p>For any questions or concerns about this Privacy Policy:</p>
                                    <p>
                                        📧 Email:{" "}
                                        <a href="mailto:tirwin.communications@tirwin.in">
                                            tirwin.communications@tirwin.in
                                        </a>
                                    </p>
                                </div>
                            </section>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
