// next-app/src/app/(main)/checkout/page.tsx
"use client";

import React, { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { CartService } from "@/services/cart.service";
import "./checkout.css";

export default function CheckoutPage() {
    const router = useRouter();
    const [cartItems, setCartItems] = useState<any[]>([]);
    const [errorMessage, setErrorMessage] = useState("");
    const [successMessage, setSuccessMessage] = useState("");
    const [isProcessing, setIsProcessing] = useState(false);
    const [isLoading, setIsLoading] = useState(true);
    const [userId, setUserId] = useState<any>(null);

    useEffect(() => {
        if (typeof window !== "undefined") {
            const storedUser = sessionStorage.getItem("user");
            const user = storedUser ? JSON.parse(storedUser) : null;
            setUserId(user);

            if (user?.id) {
                fetchCartItems(user.id);
            } else {
                setErrorMessage("User not logged in.");
                setIsLoading(false);
            }
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const fetchCartItems = async (id: string) => {
        try {
            const items = await CartService.getCartItems(id);
            setCartItems(items);
        } catch (error) {
            console.error(error);
            setErrorMessage("Failed to load cart items.");
        } finally {
            setIsLoading(false);
        }
    };

    const removeFromCart = async (itemId: string) => {
        try {
            await CartService.removeFromCart(itemId);
            setCartItems((prev) => prev.filter((item) => item.id !== itemId));
        } catch (error) {
            console.error(error);
            setErrorMessage("Failed to remove item.");
        }
    };

    const proceedToPurchase = async () => {
        if (!cartItems.length) {
            setErrorMessage("Cart is empty.");
            return;
        }

        setIsProcessing(true);
        setSuccessMessage("");
        setErrorMessage("");

        const transactions = cartItems.map((item) => ({
            webinarId: item.webinar.id,
            userId: userId?.id,
            transactionId: `TXN\${Date.now()}`,
      amount: parseFloat(item.amount),
    }));

    let successfulRegistrations = 0;
    const totalTransactions = transactions.length;

    for (let i = 0; i < totalTransactions; i++) {
        const transaction = transactions[i];
      try {
        await CartService.registerForWebinar(transaction);
        successfulRegistrations++;

        // Remove item from the cart after successful registration
        await CartService.removeFromCart(cartItems[i].id).catch(console.error);

        if (successfulRegistrations === totalTransactions) {
          setSuccessMessage("✅ Successfully registered for all webinars!");
          setIsProcessing(false);

          setTimeout(() => {
            router.push("/webinar/masterclass"); // or proper default
          }, 2000);
        }
      } catch (error) {
        console.error("Error during purchase:", error);
        setErrorMessage("❌ Failed to complete some registrations. Please try again.");
        setIsProcessing(false);
      }
    }
  };

  if (isLoading) {
    return (
      <div className="container mt-5 py-5 text-center min-vh-100" style={{ paddingTop: "100px" }}>
        <i className="fas fa-spinner fa-spin fa-2x mb-3"></i>
        <p>Loading your cart...</p>
      </div>
    );
  }

  return (
    <div className="container min-vh-100" style={{ paddingTop: "100px", paddingBottom: "60px" }}>
      <h2 className="mb-4 fw-bold">Your Cart</h2>

      {errorMessage && <div className="alert alert-danger shadow-sm border-0 rounded-3">{errorMessage}</div>}
      {successMessage && <div className="alert alert-success shadow-sm border-0 rounded-3">{successMessage}</div>}

      {cartItems.length === 0 ? (
        <div className="alert alert-info custom-alert shadow-sm border-0 rounded-3">
          Your cart is empty.{" "}
          <Link href="/webinar/masterclass" className="fw-bold">
            Browse Events
          </Link>
        </div>
      ) : (
        <>
          <div className="table-responsive shadow-sm rounded-3">
            <table className="table table-hover table-striped table-bordered mb-0 bg-white">
              <thead className="bg-primary text-white">
                <tr>
                  <th className="py-3">Event Title</th>
                  <th className="py-3">Coupon Code</th>
                  <th className="py-3">Amount</th>
                  <th className="py-3">Start Date</th>
                  <th className="py-3">End Date</th>
                  <th className="py-3 text-center">Status</th>
                  <th className="py-3 text-center">Actions</th>
                </tr>
              </thead>
              <tbody>
                {cartItems.map((item) => (
                  <tr key={item.id}>
                    <td className="align-middle fw-semibold">{item.webinar.title}</td>
                    <td className="align-middle">{item.coupon_code || "N/A"}</td>
                    <td className="align-middle">
                      {item.amount === "0.00" || item.amount === 0 ? "FREE" : `INR \${item.amount}`}
                    </td>
                    <td className="align-middle">
                      {new Date(item.webinar.start_time).toLocaleString("en-US", {
                        month: "short",
                        day: "numeric",
                        year: "numeric",
                        hour: "2-digit",
                        minute: "2-digit",
                      })}
                    </td>
                    <td className="align-middle">
                      {new Date(item.webinar.end_time).toLocaleString("en-US", {
                        month: "short",
                        day: "numeric",
                        year: "numeric",
                        hour: "2-digit",
                        minute: "2-digit",
                      })}
                    </td>
                    <td className="align-middle text-center">
                      <span
                        className={`badge \${
                          item.is_checked_out ? "bg-success" : "bg-warning text-dark"
                        } px-3 py-2 rounded-pill`}
                      >
                        {item.is_checked_out ? "Checked Out" : "Pending"}
                      </span>
                    </td>
                    <td className="align-middle text-center">
                      <button
                        className="btn btn-outline-danger btn-sm rounded-3 fw-bold px-3"
                        onClick={() => removeFromCart(item.id)}
                      >
                        <i className="fas fa-trash me-1"></i> Remove
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>

          <div className="row justify-content-end mt-4">
            <div className="col-md-4">
              <button
                className="btn btn-primary w-100 py-3 rounded-3 fw-bold shadow-sm"
                onClick={proceedToPurchase}
                disabled={isProcessing}
                style={{ background: "linear-gradient(90deg, #2563eb, #1e40af)", border: "none" }}
              >
                {isProcessing ? (
                  <>
                    <i className="fas fa-spinner fa-spin me-2"></i> Processing...
                  </>
                ) : (
                  "Proceed to Purchase"
                )}
              </button>
            </div>
          </div>
        </>
      )}
    </div>
  );
}

// src/app/pages/checkout/checkout.component.ts
import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { CartService } from './checkout.service';

@Component({
  selector: 'app-checkout',
  templateUrl: './checkout.component.html',
  styleUrls: ['./checkout.component.css']
})
export class CheckoutComponent implements OnInit {
  cartItems: any[] = [];
  errorMessage = '';
  userId: any = '';
  isProcessing = false;
  successMessage = '';

  constructor(private cartService: CartService, private router: Router) { }

  ngOnInit() {
    this.userId = JSON.parse(sessionStorage.getItem('user') ?? '{}'); // Use '{}' if null

    if (this.userId) {
      this.getCartItems();
    } else {
      this.errorMessage = 'User not logged in.';
    }
  }

  getCartItems() {
    this.cartService.getCartItems(this.userId?.id).subscribe({
      next: (items) => {
        this.cartItems = items;
      },
      error: () => {
        this.errorMessage = 'Failed to load cart items.';
      }
    });
  }

  removeFromCart(itemId: string) {
    this.cartService.removeFromCart(itemId).subscribe({
      next: () => {
        this.cartItems = this.cartItems.filter(item => item.id !== itemId);
      },
      error: () => {
        this.errorMessage = 'Failed to remove item.';
      }
    });
  }

  /** Proceed to purchase all items in the cart */
  /** Proceed to purchase all items in the cart */
  proceedToPurchase() {
    if (!this.cartItems.length) {
      this.errorMessage = 'Cart is empty.';
      return;
    }

    this.isProcessing = true;
    this.successMessage = '';
    this.errorMessage = '';

    const transactions = this.cartItems.map(item => ({
      webinarId: item.webinar.id,
      userId: this.userId?.id,
      transactionId: `TXN${Date.now()}`,
      amount: parseFloat(item.amount)
    }));

    let successfulRegistrations = 0;
    let totalTransactions = transactions.length;

    transactions.forEach((transaction, index) => {
      this.cartService.registerForWebinar(transaction).subscribe({
        next: (response) => {
          successfulRegistrations++;

          // Remove item from the cart after successful registration
          this.cartService.removeFromCart(this.cartItems[index].id).subscribe();

          // Check if all transactions are successful before showing success message
          if (successfulRegistrations === totalTransactions) {
            this.successMessage = '✅ Successfully registered for all webinars!';
            this.isProcessing = false;

            // Redirect after showing success message
            setTimeout(() => {
              this.router.navigate(['/webinar']);
            }, 2000);
          }
        },
        error: (error) => {
          console.error('Error during purchase:', error);
          this.errorMessage = '❌ Failed to complete some registrations. Please try again.';
          this.isProcessing = false;
        }
      });
    });
  }
}
<div class="container mt-5">
    <h2 class="mb-4">Your Cart</h2>
  
    <!-- Show error message if any -->
    <div *ngIf="errorMessage" class="alert alert-danger">{{ errorMessage }}</div>
    <div *ngIf="successMessage" class="alert alert-success">{{ successMessage }}</div>
  
    <!-- Show message when cart is empty -->
    <div *ngIf="cartItems.length === 0" class="alert alert-info custom-alert">
      Your cart is empty. <a routerLink="/webinar">Browse Webinars</a>
    </div>
  
    <!-- Responsive Cart Table -->
    <div class="table-responsive">
      <table class="table table-striped table-bordered">
        <thead class="bg-primary text-white">
          <tr>
            <th>Webinar Title</th>
            <th>Coupon Code</th>
            <th>Amount</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Status</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr *ngFor="let item of cartItems">
            <td>{{ item.webinar.title }}</td>
            <td>{{ item.coupon_code || 'N/A' }}</td>
            <td>{{ item.amount === '0.00' ? 'FREE' : '$' + item.amount }}</td>
            <td>{{ item.webinar.start_time | date: 'short' }}</td>
            <td>{{ item.webinar.end_time | date: 'short' }}</td>
            <td>
              <span class="badge" [ngClass]="{'badge-success': item.is_checked_out, 'badge-warning': !item.is_checked_out}">
                {{ item.is_checked_out ? 'Checked Out' : 'Pending' }}
              </span>
            </td>
            <td>
              <button class="btn btn-danger btn-sm" (click)="removeFromCart(item.id)">
                <i class="fas fa-trash"></i> Remove
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  
    <!-- Checkout Button -->
    <button class="btn btn-primary w-100 mt-3" (click)="proceedToPurchase()" [disabled]="isProcessing">
      {{ isProcessing ? 'Processing...' : 'Proceed to Purchase' }}
    </button>
  </div>
